### ISSUE TITLE
Is there a way to view a subtask when a key is specified

### ISSUE THREAD

**Issue by weiserma** [gvoss/php-mediawiki-jiki#11]
`<jira key=P-101></jira>`   gives weird result if P-101 is a sub-task

**Comment by gvoss** [comment]
Hello - I know it has been a while but I believe this is fixed as a result of #13 and I have documented how to do this.  The reason is because if you are not using `JQL` it excludes subtasks by default.  Fixed code is currently in `develop` branch.  
```
<jira key="P-101" jikiAllowSubtasks="true"></jira>
```
