### ISSUE TITLE
Can't get extension to work.  

### ISSUE THREAD

**Issue by gamiller0** [gvoss/php-mediawiki-jiki#12]
Hi,

I'm trying to get this extension to work.  I have tweaking the few settings as much as I can, but all I get when trying to impliment on a wiki page is this:

Consider using JIRA on HTTPS...

I don't see anything in the mediawiki debug logs.  I am using MediaWiki 1.30.

Can anyone help?  

Thanks.

**Comment by gvoss** [comment]
Hey @gamiller0 - JIKI expects JIRA to be hosted with SSL (so that credentials are not shared over the internet without encryption).  Is your JIRA using https and have you configured the `jikiJiraHost` variable with an https protocol?

e.g.
```
$jikiJiraHost = "https://jira.atlassian.com";
```

**Comment by gamiller0** [comment]
Hi @gvoss - thanks for the quick reply.  Can I use JIKI without SSL?  Currently don't have that set up with our JIRA instance.  Just use regular http.  

Thanks.

**Comment by gvoss** [comment]
You can and you have two options:

1. turn on self-signed ssl and then apply the example configuration here (https://github.com/gvoss/php-mediawiki-jiki#advanced-configuration).
2. remove this `if` statement (https://github.com/gvoss/php-mediawiki-jiki/blob/master/Jiki.php#L98-L103)

**Comment by gamiller0** [comment]
I'll try that, thanks!

**Comment by jamal22066** [comment]
Thank You for this extension gvoss. The world needs more people like you.
