### ISSUE TITLE
Error on empty JIRA query

### ISSUE THREAD

**Issue by gamiller0** [gvoss/php-mediawiki-jiki#13]
I have a bunch of different sections in my Wiki based on different JIRA queries.  Occasionally these sections will not return any results.  If a query is empty then MediaWiki runs into issues and returns a bunch of garbage at the top of the page (see screenshot below).  I currently have placeholder tasks so this does not happen.  Would be nice to get it fixed.  

Running MediaWiki 1.30 and Jiki 1.1

![capture](https://user-images.githubusercontent.com/20516436/38564377-065cee3a-3cad-11e8-8fc6-c53d234a8214.JPG)

**Comment by gvoss** [comment]
Hello - I know it has been a while but I have a fix for this issue in develop branch if you want to test that.
