### ISSUE TITLE
Call to undefined function curl_init

### ISSUE THREAD

**Issue by EdKok** [gvoss/php-mediawiki-jiki#5]
Hi, I tried installing this extension but did not succeed; debugging shows:

_Strict Standards: Non-static method JQL::getJQL() should not be called statically in /srv/www/htdocs/mediawiki/extensions/JIKI/Jiki.php on line 110

Strict Standards: Non-static method Rest::getJIRAData() should not be called statically in /srv/www/htdocs/mediawiki/extensions/JIKI/Jiki.php on line 133

Strict Standards: Non-static method Rest::callJIRARest() should not be called statically in /srv/www/htdocs/mediawiki/extensions/JIKI/api/Rest.php on line 37

Fatal error: **Call to undefined function curl_init**() in /srv/www/htdocs/mediawiki/extensions/JIKI/api/Rest.php on line 66_
![capture](https://cloud.githubusercontent.com/assets/26001736/23298789/4904d3b8-fa7f-11e6-858f-a241a4a2ec4f.PNG)

**Comment by gvoss** [comment]
Hey - have you installed the php curl extension on your web server?

http://stackoverflow.com/questions/4396779/fatal-error-call-to-undefined-function-curl-init-in-on-line-9

**Comment by gvoss** [comment]
@EdKok - Also are you experiencing these error messages on multiple pages?
> Strict Standards: Non-static method

I think I can probably fix this easily since it's probably a gap on my end

**Comment by EdKok** [comment]
Hi,

Thanks for your support.
Yes this happens on all pages I’ve tested on; about five.
Any other php packages needed maybe; devel?

Edit: I didnt restart Apache2 earlier and now get:
"Error while calling JIRA..." in the WiKi page (besides the "Strict Standards").
But at least no more empty/white page.

**Comment by gvoss** [comment]
Probably curl covers it - I am using RHEL so a bunch of that stuff is enabled by default for php and didn't require any additional configuration.

The Error while calling JIRA usually occurs when the username/password is wrong.  Also, if your JIRA is behind some kind of web proxy or SSO login page it might not work unless the wiki can directly access the JIRA APIs.
