### ISSUE TITLE
Operators < and > not usable in JQL queries

### ISSUE THREAD

**Issue by z0n** [gvoss/php-mediawiki-jiki#6]
I'm trying to use this JQL query in my wiki to get the issues which were open (and existing) on a specific date:
`<jira jql="project = 10804  AND status was not in (Closed, Done, Resolved) ON 2017-03-29 AND createdDate <= 2017-03-29 ORDER BY created DESC"></jira>`

However, the "<=" operator causes the extension to fail and show an error: `Error while calling JIRA...`
When removing the `createdDate <= 2017-03-29` part of the query or changing the "<=" to "=", it works fine.

**Comment by gvoss** [comment]
Hey - just confirming that you're using it properly and it's a problem with Jiki.  I have to look into it more as it seems like it is not treating the arguments properly or as expected.  It appears to be blowing up what is provided in `jql` as an array.

**Comment by gvoss** [comment]
Hey @z0n I found that if you try and put `<` or `>` into the arguments of a parser function it behaves badly (mediawiki thing) and I learned that you have to escape this using `&gt;` or `&lt`.  Additionally I made another change that was causing a problem and I added the following JQL to my list of ones that I test:

`project in (ABCD) AND createdDate >= 2014-01-01`

The latest is in develop, there is one more issue I'd like to get to before I release another release.

**Comment by z0n** [comment]
Thanks for the quick update, I can test it in a few days!

**Comment by z0n** [comment]
@gvoss: I just checked out the dev branch here and it seems to work!
`<jira jql="project = 10804 AND status was not in (Closed, Done, Resolved) ON 2017-05-11 AND createdDate &lt; 2017-05-11 ORDER BY created DESC"></jira>` correctly shows the expected result now.
