### ISSUE TITLE
In my jira instance I have some issue with unassigned component, how can I filter on those?

### ISSUE THREAD

**Issue by ykoehler** [gvoss/php-mediawiki-jiki#8]
I would like to list all the Jira issues for which no components are set.  I used the tag as follow:

<jira project="MYP" status="!Closed" issuetype="!Bug" component=""></jira>

I got

Error while calling JIRA...

**Comment by gvoss** [comment]
Hey - right now the jql implementation is really basic but you can always use the `jql` field for more complicated queries.  I would add `component is EMPTY` to a query to find all issues that have no component.
